"""Initial migration: themes, data_sources, ingestion_runs, test_runs

Revision ID: cfb5c0518e7d
Revises: 
Create Date: 2025-11-17 16:28:35.944171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb5c0518e7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_editor', sa.String(length=100), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'testing', 'approved', 'published')", name='check_theme_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.create_index('idx_theme_order', ['display_order'], unique=False)
        batch_op.create_index('idx_theme_status', ['status'], unique=False)

    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('sharepoint_url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.Column('last_file_modified', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('sheets_count', sa.Integer(), nullable=True),
    sa.Column('rows_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index('idx_datasource_last_read', ['last_read_at'], unique=False)
        batch_op.create_index('idx_datasource_theme', ['theme_id'], unique=False)
        batch_op.create_index('idx_datasource_theme_order', ['theme_id', 'display_order'], unique=False)

    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('rows_imported', sa.Integer(), nullable=True),
    sa.Column('changes_detected', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'failed')", name='check_ingestion_status'),
    sa.CheckConstraint("trigger_type IN ('automatic', 'manual')", name='check_trigger_type'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.create_index('idx_ingestion_started', ['started_at'], unique=False)
        batch_op.create_index('idx_ingestion_status', ['status'], unique=False)
        batch_op.create_index('idx_ingestion_theme', ['theme_id'], unique=False)

    op.create_table('test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('result_details', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'passed', 'failed')", name='check_test_status'),
    sa.CheckConstraint("test_type IN ('automated', 'manual')", name='check_test_type'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.create_index('idx_test_started', ['started_at'], unique=False)
        batch_op.create_index('idx_test_status', ['status'], unique=False)
        batch_op.create_index('idx_test_theme', ['theme_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_test_theme')
        batch_op.drop_index('idx_test_status')
        batch_op.drop_index('idx_test_started')

    op.drop_table('test_runs')
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_ingestion_theme')
        batch_op.drop_index('idx_ingestion_status')
        batch_op.drop_index('idx_ingestion_started')

    op.drop_table('ingestion_runs')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index('idx_datasource_theme_order')
        batch_op.drop_index('idx_datasource_theme')
        batch_op.drop_index('idx_datasource_last_read')

    op.drop_table('data_sources')
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.drop_index('idx_theme_status')
        batch_op.drop_index('idx_theme_order')

    op.drop_table('themes')
    # ### end Alembic commands ###
